#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Necesitas ejecutar este script con privilegios root."
  exit
fi

function newUser {
	usuario="$1"
	rol="$2"
	FILE=/etc/rbac/roles/$rol.conf
	if [[ ! -f "$FILE" ]]; then
		echo "El rol $rol no existe!"
		exit
	fi
	uid=`awk -F'[:]' '{print $3}' /etc/passwd | tail -n 1`
	#Buscamos el ultimo id añadido y le sumamos uno
	let uid+=1
	#Buscamos el id del grupo del rol que ha indicado el usuario
	gid=`cat /etc/group | grep $rol | awk -F[:] '{print $3}'`
	#Añadimos una linea nueva al archivo passwd con la info del usuario
	nuevoUsuario="$usuario:x:$uid:$gid:$usuario,,,:/home/$usuario:/bin/bash"
	bash -c "echo $nuevoUsuario >> /etc/passwd"
	#Añadimos una linea al archivo shadow
	bash -c "echo '$usuario:x:0:0:0::::' >> /etc/shadow"
	#Creamos su carpeta Home y lo añadimos en el grupo
	#sudo mkdir -p "/users/$rol/$usuario/home/$usuario"
	#cp -r /etc/skel "/users/$rol/$usuario/home/$usuario"
	#chown -R $usuario "/users/$rol/$usuario/home/$usuario"
	#chgrp -R $rol "/users/$rol/$usuario/home/$usuario"
	#gpasswd -A $usuario $rol
	#Guardamos una contraseña para el usuario
	echo 'Escribe tu contraseña:'
	read -s contra
	echo "$usuario":"$contra" | sudo chpasswd
	echo "Creando entorno..."
	#bash /etc/rbac/userEnvironment.sh $usuario
	echo "Generando llaves..."
	usermod -aG sudo $usuario
	bash /etc/rbac/keyGenerator.sh $usuario
}

function deleteUser {
	usuario="$1"
	if [ -z "$usuario" ]
	then
		echo "Not Found"
		exit
	fi
	rol=`sudo su $usuario -c groups`
	#Eliminamos los rastros de usuario (passwd, groups, shadow, home...)
	sed -i "/$usuario:/d" /etc/passwd
	sed -i "/$usuario:/d" /etc/shadow
    gpasswd -d $usuario $rol &>/dev/null
	rm -rf "/users/$rol/$usuario"
	find / -user $usuario -exec rm -fr {} \; 2>/dev/null
	#borramos las keys
	rm -rf /etc/rbac/p_keys/$usuario
	rm -rf /etc/rbac/ssh/$usuario
	echo "Usuario [$usuario] eliminado!"
}


if [ ! $# -gt 0 ]; then
	echo "rbac: falta un argumento"
	echo "Prueba 'rbac --help' para más información"
else 
	case $1 in
		"-nuevoUsuario")
			if [ $# -eq 3 ] 
			then
				newUser $2 $3
			else
				echo "Faltan/Sobran argumentos!"
				echo "USO: rbac -nuevoUsuario [USUARIO] [ROL]"
			fi
			;;
		"-eliminarUsuario")
		
			if [ $# -eq 2 ] 
			then
				deleteUser $2
			else
				echo "Faltan/Sobran argumentos!"
				echo "USO: rbac -eliminarUsuario [USUARIO]"
			fi
			;;
		"--help")
			echo "USO: rbac [ARGUMENTOS]"
			echo -e "Comandos disponibles:\n"
			echo "-nuevoUsuario [USUARIO] [ROL]		añade un nuevo usuario al sistema"
			echo "-eliminarUsuario [USUARIO]		elimina un usuario del sistema"
			echo "--help			muestra los comandos disponibles y una breve descripción"
			;;
		*)
			echo "USO: rbac [ARGUMENTO]"
			echo "Prueba 'rbac --help' para más información"
			;;
	esac
fi
